Section Test.
(*set-info :smt-lib-version 2.6*)
(*set-logic AUFBVDTLIA*)
(*set-info :source 
Generated by: Andrew Reynolds
Generated on: 2017-04-28
Generator: Nunchaku, Leon, CVC4, converted to v2.6 by CVC4
Application: Counterexample generation for higher-order theorem provers
Target solver: CVC4, Z3
Publications: "Model Finding for Recursive Functions in SMT" by Andrew Reynolds, Jasmin Christian Blanchette, Simon Cruanes, and Cesare Tinelli, IJCAR 2016.
*)
(*set-info :license https://creativecommons.org/licenses/by/4.0/*)
(*set-info :category industrial*)
(*set-info :status unknown*)
Inductive Tree_1015 := 
  | Leaf_1016
  | Node_1017(left_1018 : Tree_1015)(value_1019 : (_ BitVec 32))(right_1020 : Tree_1015)(rank_1021 : (_ BitVec 32))
.
Variable error_value_1022 : (_ BitVec 32).
Variable size_224 : Tree_1015 -> (_ BitVec 32).
Variable error_value_1023 : (_ BitVec 32).
Hypothesis A0 : (forall ((t_223 Tree_1015)) (= (size_224 t_223) (ite ((_ is Leaf_1016) t_223) (_ bv0 32) (ite ((_ is Node_1017) t_223) (bvadd (bvadd (size_224 (left_1018 t_223)) (_ bv1 32)) (size_224 (right_1020 t_223))) error_value_1022))) ).
Hypothesis A1 : (exists ((t_223 Tree_1015)) (not (bvsge (ite ((_ is Leaf_1016) t_223) (_ bv0 32) (ite ((_ is Node_1017) t_223) (bvadd (bvadd (size_224 (left_1018 t_223)) (_ bv1 32)) (size_224 (right_1020 t_223))) error_value_1023)) (_ bv0 32))) ).
Theorem unsat: False.
Proof.

Abort.
End Test.
